### ISSUE TITLE
Crashing compose app on OpenJDK 17-ea+15

### ISSUE THREAD

**Issue by sureshg** [JetBrains/skija#102]
I have a sample application (which basically shows some animation and FPS counter) running on the latest OpenJDK 17 (`17-ea+15` build). After some time, the application crashes with the following error.

```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Failed Surface.makeFromBackendRenderTarget(DirectContext(_ptr=0x7f7eef261bb0, refCount=1), BackendRenderTarget(_ptr=0x7f6f70ce2ab0), TOP_LEFT, BGRA_8888, ColorSpace(_ptr=0x7f7eef4442a0))
        at org.jetbrains.skija.Surface.makeFromBackendRenderTarget(Surface.java:243)
        at org.jetbrains.skija.Surface.makeFromBackendRenderTarget(Surface.java:206)
        at org.jetbrains.skiko.context.MetalContextHandler.initCanvas(MetalContextHandler.kt:35)
        at org.jetbrains.skiko.SkiaLayer.draw(SkiaLayer.kt:209)
        at org.jetbrains.skiko.redrawer.MetalRedrawer.draw(MetalRedrawer.kt:48)
        at org.jetbrains.skiko.redrawer.MetalRedrawer.access$draw(MetalRedrawer.kt:14)
        at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:23)
        at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
        at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:32)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
[820440466] FPS 21 (0-795)
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000005298ecb54, pid=86761, tid=59399
#
# JRE version: OpenJDK Runtime Environment (17.0+15) (build 17-ea+15-1230)
# Java VM: OpenJDK 64-Bit Server VM (17-ea+15-1230, mixed mode, sharing, tiered, compressed class ptrs, z gc, bsd-amd64)
# Problematic frame:
# C  [libskiko-macos-x64.dylib+0x15b54]  Java_org_jetbrains_skija_impl_RefCnt__1nGetRefCount+0x4
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# JFR recording file will be written. Location: hs_err_pid86761.jfr
#
# An error report file with more information is saved as: hs_err_pid86761.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

```
Here is the crash log - [hs_err_pid86761.log](https://github.com/JetBrains/skija/files/6210943/hs_err_pid86761.log)

**Comment by tonsky** [comment]
How much time? What’s your hardware? Works fine for me, even on JDK 17

**Comment by tonsky** [comment]
Reported to Skiko, seems like double close on their side somewhere https://github.com/JetBrains/skiko/issues/84

**Comment by sureshg** [comment]
Thanks. I got it only once after running the app for 2 or 3 minutes. The following are the h/w details

```
Mac OS Catalina 10.15.7
2.9 GHz 6-Core Intel Core i9
MacBook Pro (15-inch, 2018)
Intel UHD Graphics 630 1536 MB
```
