### ISSUE TITLE
Clojure-snake example fails to run

### ISSUE THREAD

**Issue by OliverM** [JetBrains/skija#119]
Hi,

I can't launch the Clojure Snake game example. I've built Skija locally and I'm on OpenJDK v. 15, clojure v. 1.10.3. When I run `./script/run.py` I get the following error:

```sh
WARNING: Use of :paths external to the project has been deprecated, please remove: ../../native/build
WARNING: Use of :paths external to the project has been deprecated, please remove: ../../shared/target/classes
Syntax error (ClassNotFoundException) compiling at (snake/game.clj:33:1).
org.jetbrains.skija.macos.x64.LibraryFinder

Full report at:
/var/folders/b2/y853n0sx0qjf3qyd9bljffl40000gn/T/clojure-17561839386300608711.edn

Traceback (most recent call last):
  File "/Users/oliver/Projects/skija/examples/clojure-snake/./script/run.py", line 11, in <module>
    sys.exit(main())
  File "/Users/oliver/Projects/skija/examples/clojure-snake/./script/run.py", line 7, in main
    subprocess.check_call(["clj", "-M:" + system, "-m", "snake.main"])
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['clj', '-M:macos', '-m', 'snake.main']' returned non-zero exit status 1.
```

The skija test suite passes for my local build.

Any pointers? Thanks for Skija!

**Comment by tonsky** [comment]
Fixed the paths, let me know how it goes

**Comment by OliverM** [comment]
Just tested it, all good! Thanks for the quick fix 🎉
